CREATE SEQUENCE seqCours START WITH 1;
CREATE TABLE Cours
(
    Nr  NUMBER,
    Nom VARCHAR2(20)
);

DECLARE
    VNr Cours.Nr%TYPE;
BEGIN
    INSERT INTO Cours VALUES (SeqCours.NEXTVAL, 'SGBD');
    SELECT Nr INTO VNr FROM Cours WHERE RTRIM(Nom) = 'SGBD';
    DBMS_OUTPUT.PUT_LINE('VNr = ' || VNr);
    INSERT INTO Cours VALUES (SeqCours.NEXTVAL, 'C#');
    SELECT Nr INTO VNr FROM Cours WHERE RTRIM(Nom) = 'C#';
    DBMS_OUTPUT.PUT_LINE('VNr = ' || VNr);
    SELECT SeqCours.CURRVAL INTO VNr FROM DUAL;
    DBMS_OUTPUT.PUT_LINE('VNr =' || VNr);
END;
