CREATE DATABASE NomBase;
CREATE TABLESPACE NomTableSpace;
CREATE ROLLBACK SEGMENT NomSegment;
CREATE USER sgbdTest IDENTIFIED BY sgbdTest
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  PROFILE DEFAULT ACCOUNT UNLOCK;